version: '{build}'
image: Visual Studio 2015
install:
- cmd: >-
    mkdir build

    cd build

    cmake ..\src
artifacts:
- path: build\asar\Release\asar-standalone.exe
- path: build\asar\Release\asar.dll
configuration: Release
platform: Win32
test_script:
  - cmd: >-
      cd %APPVEYOR_BUILD_FOLDER%

      mkdir tests_tmp

      build\asar-dll-test\Release\asar-dll-test.exe build\asar\Release\asar.dll tests dummy_rom.sfc %APPVEYOR_BUILD_FOLDER%\tests_tmp